apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ingress-requests
  namespace: webapp
spec:
  scaleTargetRef:
    kind:          Deployment        
    name:          webapp            
  pollingInterval:  15               
  cooldownPeriod:   30               
  minReplicaCount:  2                
  maxReplicaCount:  15                  
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://webapp-prom-prometheus-server.monitoring.svc.cluster.local
      metricName: nginx_ingress_controller_requests
      threshold: '5'
      query: sum(rate(nginx_ingress_controller_requests{path="/"}[2m]))